name: Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: julia-actions/setup-julia@latest
      with:
        version: '1.12'

    - name: Install docs environment
      run: julia -e "using Pkg; Pkg.develop(path=ENV['GITHUB_WORKSPACE']); Pkg.instantiate(); Pkg.precompile()"

    - name: Build docs
      run: julia --project=docs docs/make.jl
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build
